### PR TITLE
remove redundancy in utils.py

### PR DESCRIPTION
**Pull request by 3110**
Please merge this If you like.

### CODE REVIEW

**Comment by zlj-zz** [comment]
It's seem better. Thanks.

**Comment by zlj-zz** [comment]
I have a question. Is this also OK in Python 2? @3110

**Comment by 3110** [comment]
@zlj-zz Yes, I have also tested on Python 2.7.18.

**Comment by zlj-zz** [comment]
Ok, it's great.  Your code is very concise.  😊

**Pull request merged**
